# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JDMobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Value', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='Code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='parameter',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JDMobile.Mobile'),
        ),
    ]
