# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JDMobile', '0002_auto_20170706_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='Value',
            new_name='value',
        ),
    ]
