# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JDMobile', '0003_auto_20170706_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'Mobile'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_PID', to='JDMobile.Mobile'),
        ),
    ]
