# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDMobile', '0005_auto_20170718_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
