# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JDMobile', '0006_auto_20170718_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={},
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='PID',
            new_name='p_PID',
        ),
    ]
